#pragma config(Motor,  port2,           baseLeft,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           baseRight,     tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port4,           armLeft,       tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port5,           armRight,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           clawMotor,     tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX2) // This code is for the VEX cortex platform

#pragma competitionControl(Competition) // Select Download method as "competition"

#include "Vex_Competition_Includes.c"  //Main competition background code

/*---------------------------------------------------------------------------*/
/*                              End of Pragmas                               */
/*---------------------------------------------------------------------------*/

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Pre-Autonomous                               */
/*                                                                           */
/*---------------------------------------------------------------------------*/


void pre_auton()
{

	bStopTasksBetweenModes = true;  // Keeps created tasks running between modes

}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous                                   */
/*                                                                           */
/*---------------------------------------------------------------------------*/


task autonomous()
{

	AutonomousCodePlaceholderForTesting(); // Remove once code has been written

}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
	while(true)
	{

		//Drive


		motor[baseLeft]  = (vexRT[Ch1] + vexRT[Ch2])/2;  // (y + x)/2
    motor[baseRight] = (vexRT[Ch1] - vexRT[Ch2])/2;  // (y - x)/2





		//ArmMotor for Claw
    motor[armRight] = (vexRT[Ch3]);
    motor[armLeft] = (vexRT[Ch3]);


    /*
    	if(vexRT[Btn6U] == 1)
		{
			motor[armRight] = 127;
			motor[armLeft] = 127;
		}
		else if(vexRT[Btn6D] == 1)
		{
			motor[armRight] = -127;
			motor[armLeft] = -127;
		}
		else
			motor[armRight] = 10;
			motor[armLeft] = 127;
		}
		*/

		if(vexRT[Btn5U] == 1)
		{
			motor[clawMotor] = 127;
		}
		else if(vexRT[Btn5D] == 1)
		{
			motor[clawMotor] = -127;
		}
		else
		{
			motor[clawMotor] = 0;
		}

	}
}
