#pragma config(Sensor, dgtl1,  shaftencoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl9,  sonarSensor,    sensorSONAR_cm)
#pragma config(Sensor, dgtl11, pistonforward,  sensorDigitalOut)
#pragma config(Sensor, dgtl12, pistonbackward, sensorDigitalOut)
#pragma config(Motor,  port2,           leftside,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           lift,          tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           clawMotor,     tmotorNone, openLoop)
#pragma config(Motor,  port5,           armMotor,      tmotorNone, openLoop)
#pragma config(Motor,  port6,           rightside,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           lifttwo,       tmotorVex393_MC29, openLoop, encoderPort, None)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
void stop(){
motor[leftMotor] = 0; //Full power is 127
motor[rightMotor] = 0; //Full power is 127
motor[armMotor] = 0;
motor[clawMotor] = 0;
wait1Msec(duration); //Run for time
}
*/





void armup(int duration){
	motor[armMotor] = -127;
	wait1Msec(duration);
}

void armdown(int duration){
	motor[armMotor] = 127;
	wait1Msec(duration);
}

void clawopen(int duration){
	motor[clawMotor] = -127;
	wait1Msec(duration);
}

void clawclose(int duration){
	motor[clawMotor] = 127;
	wait1Msec(duration);
}

void grabLift(int duration){
	motor[clawMotor] = 127;
	wait1Msec(duration);

}

void grabLiftTwo(int duration) {
	motor[armMotor] = 127;
	wait1Msec(duration);
}

void grabDrop(int duration){
	motor[clawMotor] = -127;
	wait1Msec(duration);

}

void grabDropTwo(int duration) {
	motor[armMotor] = -127;
	wait1Msec(duration);
}

void halfturn(int duration) {
	motor[leftside] = 127;
	motor[rightside] = -127;
	wait1Msec(duration);
}


	float ticksToMM(int ticks){
		//return ticks * 0.304778121;
		float inchInMM = 25.4;
		float ticksPerRotation = 360.0;
		float diameter = 2.75;
		float mmPerTick = (diameter * inchInMM) * PI / ticksPerRotation;
		return ticks * mmPerTick;

	}

	int distToPower(float dist, float target) {
		float fade = 200.0;
		int maxPower = 100;
		int lowPower = 20;
		int power = maxPower;
		if (dist > (target - fade)) {
			power = ((maxPower - lowPower) * ((target - dist) / fade )) + lowPower;
		}
		return power;
	}

	void forwardToDistance(float target)
	{
		SensorValue[shaftencoder] = 0;
		float dist = 0;

		while(dist < target)  // While less than 5 rotations on the leftEncoder...
		{
			dist = ticksToMM(SensorValue[shaftencoder]);
			int power = distToPower(dist, target);
			motor[leftside] = power; //Full power is 127
			motor[rightside] = power; //Full power is 127
		}
		motor[leftside] = 0; //Full power is 127
		motor[rightside] = 0; //Full power is 127
	}

	void turnLeft(int duration){
		motor[rightside] = 127;
		motor[leftside] = -127;

		wait1Msec(duration);
		motor[leftside] = 0; //Full power is 127
		motor[rightside] = 0; //Full power is 127

	}

	void turnRight(int duration){\
		motor[rightside] = -127;
		motor[leftside] = 127;

		wait1Msec(duration);
		motor[leftside] = 0; //Full power is 127
		motor[rightside] = 0; //Full power is 127

	}




task main()
{
	/*
		forwardToDistance(1180.0);
		turnLeft(280);
		turnRight(600);
		forwardToDistance(1000.0);
		*/



	while(1==1)
	{



		motor[leftside] = vexRT[Ch3];
		motor[rightside] = vexRT[Ch2];

		if((vexRT[Btn7D]) == 1)
		{
			halfturn(800);
		}


		if(vexRT[Btn6U] == 1)
		{
			motor[lift] = 127;
			motor[lifttwo] = 127;

		}
		else if(vexRT[Btn6D] == 1)
		{
			motor[lift] = -127;
			motor[lifttwo] = -127;

		}
		else
		{
			motor[lift] = 0;
			motor[lifttwo] = 0;

		}

		if(vexRT[Btn8U] == 1)
		{
			SensorValue(pistonforward) = 1;

			SensorValue(pistonbackward) = 0;
		}

		if(vexRT[Btn8D] == 1)
		{
			SensorValue(pistonbackward) = 1;
			SensorValue(pistonforward) = 0;

		}
		else
		{
		}




		if((vexRT[Btn6U]) == 1)
		{
			motor[armMotor] = 127;
		}

		else if((vexRT[Btn6D]) == 1)
		{
			motor[armMotor] = -127;
		}
		else
		{
			motor[armMotor] = 10;
		}

		if((vexRT[Btn5U]) == 1)
		{
			motor[clawMotor] = 127;
		}
		else if((vexRT[Btn5D]) == 1)
		{
			motor[clawMotor] = -127;
		}
		else
		{
			motor[clawMotor] = 0;
		}


		if((vexRT[Btn7D]) == 1)
		{
			grabLift(500);
			grabLiftTwo(1000);}

		if((vexRT[Btn7U]) == 1)
		{
			grabDropTwo(700);
			grabDrop(500);
			armup(850);
		}

	}


}
