#pragma config(Motor,  port2,           rightFrontMotor, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           rightBackMotor, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           leftarm,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           rightarm,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           claw,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           leftFrontMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           leftBackMotor, tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks
	// running between Autonomous and Driver controlled modes. You will need to
	// manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	/*
	IF 5u
	then Position = RED_POLES
	5d = red flags = 1

	6u = blue poles = 2
	6d = blue flags = 3
	*/



	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
	AutonomousCodePlaceholderForTesting();
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
	// User control code here, inside the loop
	int joy_x;            // will hold the X value of the analog stick (choices below)
	int joy_y;            // will hold the Y value of the analog stick (choices below)
	int joy_c;
	int threshold = 10;   // helps to eliminate 'noise' from a joystick that isn't perfectly at (0,0)
	int leftSpeed = 0 ;
	int rightSpeed = 0;
	int liftSpeed = 0;


	while (true)
	{
		// This is the main execution loop for the user control program.
		// Each time through the loop your program should update motor + servo
		// values based on feedback from the joysticks.

		// ........................................................................
		// Insert user code here. This is where you use the joystick values to
		// update your motors, etc.
		// ........................................................................

		joy_x = vexRT[Ch1];   // This is the RIGHT analog stick.  For LEFT, change 'Ch1' to 'Ch4'.
		joy_y = vexRT[Ch2];   // This is the RIGHT analog stick.  For LEFT, change 'Ch2' to 'Ch3'.
		joy_c = vexRT[Ch4];

		// Forward, and swing turns: (both abs(X) and abs(Y) are above the threshold, and Y is POSITIVE)
		if((abs(joy_x) > threshold) && (abs(joy_y) > threshold) && (joy_y > 0))
		{
			leftSpeed  = (joy_y + joy_x)/2;
			rightSpeed = (joy_y - joy_x)/2;
		}
		// Backwards and swing turns: (both abs(X) and abs(Y) are above the threshold, and Y is NEGATIVE)
		else if((abs(joy_x) > threshold) && (abs(joy_y) > threshold) && (joy_y < 0))
		{
			leftSpeed  = (joy_y - joy_x)/2;
			rightSpeed = (joy_y + joy_x)/2;
		}
		// Turning in place: (abs(X) is above the threshold, abs(Y) is below the threshold)
		else if((abs(joy_x) > threshold) && (abs(joy_y) < threshold))
		{
			leftSpeed  = joy_x;
			rightSpeed = (-1 * joy_x);
		}
		// Standing still: (both abs(X) and abs(Y) are below the threshold)
		else
		{
			leftSpeed  = 0;
			rightSpeed = 0;
		}

		motor[leftFrontMotor] = leftSpeed;
		motor[leftBackMotor] = leftSpeed;

		motor[rightFrontMotor] = rightSpeed;
		motor[rightBackMotor] = rightSpeed;



		if(vexRT[Btn5U] == 1)       	//If button 5U is pressed...
		{
			liftSpeed = 127;    	//...raise the arm.
		}
		else if(vexRT[Btn5D] == 1)  	//Else, if button 5D is pressed...
		{
			liftSpeed = -127;	//...lower the arm.
		}
		else                      		//Else (neither button is pressed)...
		{
			liftSpeed = 0;      	//...stop the arm.
		}

		motor[leftarm] = liftSpeed;
		motor[rightarm] = liftSpeed;

		// Remove this function call once you have "real" code.
		//UserControlCodePlaceholderForTesting();
	}

}
